/**
 * Export analysis results to text format
 */

import { AnalysisData } from '@/app/components/features/AnalysisResults/AnalysisResults.types';

export function exportAnalysisToText(data: AnalysisData): string {
  const sections: string[] = [];

  // Title
  sections.push('='.repeat(60));
  sections.push('記事分析結果');
  sections.push('='.repeat(60));
  sections.push('');

  // Suggested Titles
  if (data.suggestedTitles && data.suggestedTitles.length > 0) {
    sections.push('【タイトル案】');
    sections.push('-'.repeat(60));
    data.suggestedTitles.forEach((title, index) => {
      sections.push(`${index + 1}. ${title}`);
    });
    sections.push('');
  }

  // Insights
  if (data.insights) {
    sections.push('【インサイト】');
    sections.push('-'.repeat(60));

    if (data.insights.oneLiner) {
      sections.push(`■ 一文要約`);
      sections.push(data.insights.oneLiner);
      sections.push('');
    }

    if (data.insights.whatYouLearn && data.insights.whatYouLearn.length > 0) {
      sections.push('■ 学べること');
      data.insights.whatYouLearn.forEach((item, index) => {
        sections.push(`  ${index + 1}. ${item}`);
      });
      sections.push('');
    }

    if (data.insights.benefits && data.insights.benefits.length > 0) {
      sections.push('■ メリット');
      data.insights.benefits.forEach((item, index) => {
        sections.push(`  ${index + 1}. ${item}`);
      });
      sections.push('');
    }

    if (data.insights.recommendedFor && data.insights.recommendedFor.length > 0) {
      sections.push('■ おすすめ読者');
      data.insights.recommendedFor.forEach((item, index) => {
        sections.push(`  ${index + 1}. ${item}`);
      });
      sections.push('');
    }
  }

  // Eye Catch Image
  if (data.eyeCatchImage) {
    sections.push('【アイキャッチ画像】');
    sections.push('-'.repeat(60));

    if (data.eyeCatchImage.summary) {
      sections.push(`■ 要約`);
      sections.push(data.eyeCatchImage.summary);
      sections.push('');
    }

    if (data.eyeCatchImage.mainPrompt) {
      sections.push('■ 画像生成プロンプト（英語）');
      sections.push(data.eyeCatchImage.mainPrompt);
      sections.push('');
    }

    if (data.eyeCatchImage.compositionIdeas && data.eyeCatchImage.compositionIdeas.length > 0) {
      sections.push('■ 構図アイデア');
      data.eyeCatchImage.compositionIdeas.forEach((idea, index) => {
        sections.push(`  ${index + 1}. ${idea}`);
      });
      sections.push('');
    }

    if (data.eyeCatchImage.mood || data.eyeCatchImage.style) {
      sections.push('■ スタイル情報');
      if (data.eyeCatchImage.mood) {
        sections.push(`  ムード: ${data.eyeCatchImage.mood}`);
      }
      if (data.eyeCatchImage.style) {
        sections.push(`  スタイル: ${data.eyeCatchImage.style}`);
      }
      sections.push('');
    }

    if (data.eyeCatchImage.colorPalette && data.eyeCatchImage.colorPalette.length > 0) {
      sections.push('■ カラーパレット');
      sections.push(`  ${data.eyeCatchImage.colorPalette.join(', ')}`);
      sections.push('');
    }
  }

  // Hashtags
  if (data.hashtags && data.hashtags.length > 0) {
    sections.push('【ハッシュタグ】');
    sections.push('-'.repeat(60));
    // Display hashtags in rows of 5
    for (let i = 0; i < data.hashtags.length; i += 5) {
      const row = data.hashtags.slice(i, i + 5).join('  ');
      sections.push(row);
    }
    sections.push('');
    sections.push('■ コピー用（スペース区切り）');
    sections.push(data.hashtags.join(' '));
    sections.push('');
  }

  // Series Ideas
  if (data.seriesIdeas && data.seriesIdeas.length > 0) {
    sections.push('【シリーズ記事案】');
    sections.push('-'.repeat(60));
    data.seriesIdeas.forEach((idea, index) => {
      sections.push(`${index + 1}. ${idea.title}`);
      sections.push(`   説明: ${idea.description}`);
      sections.push(`   対象読者: ${idea.targetAudience}`);
      sections.push('');
    });
  }

  // Footer
  sections.push('='.repeat(60));
  sections.push(`生成日時: ${new Date().toLocaleString('ja-JP')}`);
  sections.push('Generated by note Hashtag AI Generator');
  sections.push('='.repeat(60));

  return sections.join('\n');
}

export function downloadTextFile(content: string, filename: string = 'analysis-result.txt') {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
